.TH MYCAT 3 "21 Sep 2025" "Version 1.0" "User Commands"
.SH NAME
mycat \- concatenate and display files
.SH SYNOPSIS
.B mycat
[\fIOPTIONS\fR] [\fIFILE\fR]...
.SH DESCRIPTION
The mycat function reads the content of the given files and displays it to standard output.
It can take multiple files as input and will concatenate them in the order specified.
.SH AUTHOR
Ayesha Akbar <ayeshaakbar@gmail.com>
